"""
Mock Utilities for Development & Testing
==========================================

[MOCK] — All functions in this file generate MOCK/SYNTHETIC data for
testing and demonstrating the XAI pipeline. These are NOT real outputs
from upstream modules.

These mock functions should be replaced with real module outputs when:
- Sravani / Dominic deliver the classification model → replace create_mock_classification_output
- Aryaahi delivers the segmentation module → replace create_mock_severity_output

Author: Vidhi Garg
"""

import sys
import os
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms


def create_mock_classification_output(
    model: torch.nn.Module,
    image_path: str,
    classes: List[str],
    device: torch.device,
    preprocess_fn=None,
) -> Dict[str, Any]:
    """
    [MOCK] Run inference using the existing model and return a standardized
    classification output dict.

    This mimics the expected upstream classification contract:
        {
            "predicted_class": "Tomato___Late_blight",
            "confidence": 0.94,
            "model": trained_pytorch_model
        }

    When the real classification module from Sravani or Dominic is ready,
    replace this function with their actual output.

    Args:
        model: Trained PyTorch model (nn.Module).
        image_path: Path to the input leaf image.
        classes: List of class label strings.
        device: torch device (cpu/cuda).
        preprocess_fn: Optional preprocessing transform. If None, uses
                       a basic resize + normalize pipeline.

    Returns:
        Dict with predicted_class, confidence, model reference, and input_tensor.
    """
    if preprocess_fn is None:
        # Basic preprocessing — for accurate results with the hybrid model,
        # use the transforms from data_loader.py (BilateralFilter + VegetationIndices)
        preprocess_fn = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])

    image = Image.open(image_path).convert("RGB")
    input_tensor = preprocess_fn(image).unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        logits = model(input_tensor)
        probabilities = F.softmax(logits, dim=1)[0]
        confidence, predicted_idx = torch.max(probabilities, dim=0)

    return {
        "predicted_class": classes[predicted_idx.item()],
        "confidence": float(confidence.item()),
        "model": model,
        "input_tensor": input_tensor,
        "source": "[MOCK] — generated by mock_utils.create_mock_classification_output",
    }


def create_mock_severity_mask(
    height: int = 224,
    width: int = 224,
    num_spots: int = 3,
    spot_radius_range: Tuple[int, int] = (15, 40),
    seed: int = 42,
) -> np.ndarray:
    """
    [MOCK] Generate a synthetic disease severity mask with random circular lesions.

    This is NOT a real segmentation output. It creates random circular "infected"
    regions to demonstrate the severity calculation pipeline.

    Replace with Aryaahi's real segmentation mask when available.

    Args:
        height: Image height in pixels.
        width: Image width in pixels.
        num_spots: Number of simulated disease spots.
        spot_radius_range: Min and max radius for circular lesions.
        seed: Random seed for reproducibility.

    Returns:
        Binary mask (H, W) as uint8 array where 1 = infected pixel.
    """
    rng = np.random.RandomState(seed)
    mask = np.zeros((height, width), dtype=np.uint8)

    for _ in range(num_spots):
        # Random center position
        cx = rng.randint(spot_radius_range[1], width - spot_radius_range[1])
        cy = rng.randint(spot_radius_range[1], height - spot_radius_range[1])
        radius = rng.randint(spot_radius_range[0], spot_radius_range[1])

        # Draw filled circle
        yy, xx = np.ogrid[:height, :width]
        circle = (xx - cx) ** 2 + (yy - cy) ** 2 <= radius ** 2
        mask[circle] = 1

    return mask


def create_mock_severity_output(
    image_shape: Tuple[int, int] = (224, 224),
    seed: int = 42,
) -> Dict[str, Any]:
    """
    [MOCK] Generate a mock upstream severity output dict.

    This mimics the expected contract from Aryaahi's segmentation module:
        {
            "severity_mask": np.ndarray,  # binary mask (H, W)
            "leaf_mask": np.ndarray or None,
            "severity_percentage": float
        }

    Args:
        image_shape: (height, width) of the image.
        seed: Random seed.

    Returns:
        Dict with severity_mask, leaf_mask (None), and severity_percentage.
    """
    mask = create_mock_severity_mask(
        height=image_shape[0],
        width=image_shape[1],
        seed=seed,
    )

    # Calculate severity from the mock mask
    severity_pct = (mask.sum() / mask.size) * 100.0

    return {
        "severity_mask": mask,
        "leaf_mask": None,  # No leaf mask in mock — assumes full image is leaf
        "severity_percentage": round(float(severity_pct), 2),
        "source": "[MOCK] — generated by mock_utils.create_mock_severity_output",
    }


def create_mock_severity_history(
    pattern: str = "increasing",
    num_observations: int = 4,
    seed: int = 42,
) -> List[Tuple[int, float]]:
    """
    [MOCK] Generate synthetic historical severity observations for forecasting.

    This is NOT real temporal data. PlantVillage does not provide time-series
    severity data. This is purely for demonstrating the forecasting pipeline.

    Args:
        pattern: Type of trend — "increasing", "decreasing", or "stable".
        num_observations: Number of observation points to generate.
        seed: Random seed.

    Returns:
        List of (day_number, severity_percentage) tuples.
    """
    rng = np.random.RandomState(seed)

    if pattern == "increasing":
        # Simulate spreading disease
        days = [1 + i * 2 for i in range(num_observations)]
        base_severities = np.linspace(10, 50, num_observations)
        noise = rng.normal(0, 2, num_observations)
        severities = np.clip(base_severities + noise, 0, 100)
    elif pattern == "decreasing":
        # Simulate recovering plant
        days = [1 + i * 2 for i in range(num_observations)]
        base_severities = np.linspace(60, 20, num_observations)
        noise = rng.normal(0, 2, num_observations)
        severities = np.clip(base_severities + noise, 0, 100)
    else:
        # Stable
        days = [1 + i * 2 for i in range(num_observations)]
        base_severities = np.full(num_observations, 25.0)
        noise = rng.normal(0, 1, num_observations)
        severities = np.clip(base_severities + noise, 0, 100)

    return [(int(d), round(float(s), 1)) for d, s in zip(days, severities)]


def get_inference_preprocess():
    """
    [MOCK] Get the preprocessing pipeline matching the trained hybrid model.

    This imports BilateralFilter and VegetationIndices from the existing
    data_loader.py module. If those are not available (e.g., running in
    isolation), falls back to a basic transform.

    Returns:
        torchvision.transforms.Compose
    """
    try:
        # Add parent src/ to path so we can import data_loader
        src_dir = os.path.join(os.path.dirname(__file__), "..")
        if src_dir not in sys.path:
            sys.path.insert(0, os.path.abspath(src_dir))

        from data_loader import BilateralFilter, VegetationIndices

        return transforms.Compose([
            transforms.Resize((224, 224)),
            BilateralFilter(),
            VegetationIndices(),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])
    except ImportError:
        print(
            "[WARNING] Could not import BilateralFilter/VegetationIndices from "
            "data_loader.py. Using basic preprocessing. Results may differ from "
            "the trained model's expected input."
        )
        return transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])
